/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.supercompany.miragemanager.ihm.connexion;

import com.supercompany.miragemanager.ihm.Canvas;
import com.supercompany.miragemanager.ihm.popup.ErrorPopUp;
import com.supercompany.miragemanager.services.RMIManagerClientService;
import fr.jaschavolp.m1.jee.mirageshared.shared.exceptions.LoginIncorrectException;
import fr.jaschavolp.m1.jee.mirageshared.shared.services.ServicesManagerRemote;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;

/**
 *
 * @author FlorianDELSOL
 */
public class CanvasDeConnexion extends javax.swing.JFrame {

    /**
     * Service par lequel le client communique avec le serveur
     */
    private final ServicesManagerRemote service;
    
    /**
     * Creates new form CanvasDeConnexion
     */
    public CanvasDeConnexion() throws NamingException {
        initComponents();
        service = new RMIManagerClientService().getDabRemoteSvc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabelConnectTitre = new javax.swing.JLabel();
        jPanelForm = new javax.swing.JPanel();
        jLabelEmailTitre = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonConnexion = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(50, 50, 98));
        setResizable(false);

        background.setBackground(new java.awt.Color(50, 50, 98));

        jLabelConnectTitre.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelConnectTitre.setForeground(new java.awt.Color(240, 240, 240));
        jLabelConnectTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConnectTitre.setText("Connexion");

        jPanelForm.setBackground(new java.awt.Color(50, 50, 98));

        jLabelEmailTitre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmailTitre.setText("Email :");

        jButtonConnexion.setBackground(new java.awt.Color(50, 50, 98));
        jButtonConnexion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConnexion.setText("se connecter");
        jButtonConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnexionActionPerformed(evt);
            }
        });

        jLabelError.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonConnexion, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jLabelEmailTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailTitre)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButtonConnexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelConnectTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addComponent(jPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(jLabelConnectTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnexionActionPerformed
        if(!jTextFieldEmail.getText().isEmpty()){
            try {
                int managerID = service.authentifierManager(jTextFieldEmail.getText());
                Canvas canvas = Canvas.getCanvasInstance();
                canvas.setIdentifiantManager(managerID);
                canvas.setVisible(true);
                dispose();
            } catch (LoginIncorrectException ex) {
                ErrorPopUp popUp = new ErrorPopUp("erreur : " + ex.getMessage());
                Logger.getLogger(CanvasDeConnexion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonConnexionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButtonConnexion;
    private javax.swing.JLabel jLabelConnectTitre;
    private javax.swing.JLabel jLabelEmailTitre;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables
}
