/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.supercompany.miragemanager.ihm;

import com.supercompany.miragemanager.ihm.creer.JPanelCreerDemandeCompetences;
import com.supercompany.miragemanager.ihm.details.JPanelDetailsEquipe;
import com.supercompany.miragemanager.ihm.popup.ErrorPopUp;
import com.supercompany.miragemanager.ihm.table.CellRenderer.BlueTableColoredCellRenderer;
import com.supercompany.miragemanager.ihm.table.CellRenderer.MatriceTableColoredCellRenderer;
import com.supercompany.miragemanager.ihm.table.TableModel.DmdCompetenceTableModel;
import com.supercompany.miragemanager.services.RMIManagerClientService;
import fr.jaschavolp.m1.jee.mirageshared.dmdcompetences.DmdCompetencesVM;
import fr.jaschavolp.m1.jee.mirageshared.equipe.DetailsEquipeVM;
import fr.jaschavolp.m1.jee.mirageshared.shared.exceptions.IdentifiantInvalideException;
import fr.jaschavolp.m1.jee.mirageshared.shared.services.ServicesManagerRemote;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 * Structure une JFrame de l'application MIA pour les Managers
 * @author FlorianDELSOL
 */
public class Canvas extends javax.swing.JFrame {
    
    /**
     * Singleton
     */
    private static Canvas canvas;
    
    /**
     * Identifiant du Manager
     */
    private int identifiantManager;
    
    /**
     * Service par lequel le client communique avec le serveur
     */
    private final ServicesManagerRemote service;

    /**
     * Créer une nouvelle instance de classe Canvas (pour l'application MIA-Manager)
     * @throws javax.naming.NamingException
     */
    private Canvas() throws NamingException {
        initComponents();
        service = new RMIManagerClientService().getDabRemoteSvc();
        setVisible(true);
        jLabelTitle.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jSplitPane = new javax.swing.JSplitPane();
        leftSplitBackground = new javax.swing.JPanel();
        boutons = new javax.swing.JPanel();
        jButtonDemandesDeCompetences = new javax.swing.JButton();
        jButtonEquipe = new javax.swing.JButton();
        jPanelTitreApplication = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rightSplitBackground = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jScrollPaneBody = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));
        setSize(new java.awt.Dimension(960, 540));

        background.setBackground(new java.awt.Color(255, 255, 255));

        leftSplitBackground.setBackground(new java.awt.Color(50, 50, 98));

        boutons.setBackground(new java.awt.Color(50, 50, 98));
        boutons.setEnabled(false);
        boutons.setLayout(new java.awt.GridLayout(10, 0));

        jButtonDemandesDeCompetences.setBackground(new java.awt.Color(50, 50, 98));
        jButtonDemandesDeCompetences.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDemandesDeCompetences.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDemandesDeCompetences.setText("Mes demandes");
        jButtonDemandesDeCompetences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDemandesDeCompetencesActionPerformed(evt);
            }
        });
        boutons.add(jButtonDemandesDeCompetences);

        jButtonEquipe.setBackground(new java.awt.Color(50, 50, 98));
        jButtonEquipe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEquipe.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEquipe.setText("Equipe");
        jButtonEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEquipeActionPerformed(evt);
            }
        });
        boutons.add(jButtonEquipe);

        jPanelTitreApplication.setBackground(new java.awt.Color(50, 50, 98));

        jLabel3.setFont(new java.awt.Font("Vladimir Script", 0, 33)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MIA for Managers");

        javax.swing.GroupLayout jPanelTitreApplicationLayout = new javax.swing.GroupLayout(jPanelTitreApplication);
        jPanelTitreApplication.setLayout(jPanelTitreApplicationLayout);
        jPanelTitreApplicationLayout.setHorizontalGroup(
            jPanelTitreApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreApplicationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitreApplicationLayout.setVerticalGroup(
            jPanelTitreApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreApplicationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout leftSplitBackgroundLayout = new javax.swing.GroupLayout(leftSplitBackground);
        leftSplitBackground.setLayout(leftSplitBackgroundLayout);
        leftSplitBackgroundLayout.setHorizontalGroup(
            leftSplitBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boutons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTitreApplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftSplitBackgroundLayout.setVerticalGroup(
            leftSplitBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSplitBackgroundLayout.createSequentialGroup()
                .addComponent(jPanelTitreApplication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boutons, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(leftSplitBackground);

        rightSplitBackground.setBackground(new java.awt.Color(50, 50, 98));

        jPanelHeader.setBackground(new java.awt.Color(50, 50, 98));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Titre de la page");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPaneBody.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout rightSplitBackgroundLayout = new javax.swing.GroupLayout(rightSplitBackground);
        rightSplitBackground.setLayout(rightSplitBackgroundLayout);
        rightSplitBackgroundLayout.setHorizontalGroup(
            rightSplitBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPaneBody)
        );
        rightSplitBackgroundLayout.setVerticalGroup(
            rightSplitBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSplitBackgroundLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneBody, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
        );

        jSplitPane.setRightComponent(rightSplitBackground);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Traitement qui s'execute à la suite d'un clic sur le bouton "Mon équipe" du menu
     * @param evt 
     */
    private void jButtonEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEquipeActionPerformed
        goToDetailEquipe();
    }//GEN-LAST:event_jButtonEquipeActionPerformed

    /**
     * Traitement qui s'execute à la suite d'un clic sur le bouton "Mes demandes" du menu
     * @param evt 
     */
    private void jButtonDemandesDeCompetencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDemandesDeCompetencesActionPerformed
        goToListeDemandeCompetence();
    }//GEN-LAST:event_jButtonDemandesDeCompetencesActionPerformed

    /**
     * Change le Panel "Body" présent dans la jFrame (Partie en bas à droite)
     * @param p 
     */
    private void changerPanel(JPanel p){
        jScrollPaneBody.setViewportView(p);
        this.repaint();
        this.revalidate();
        this.repaint();
    }
    
    /**
     * Charge une page blanche (vide)
     */
    public void goToNothing(){
        JPanel jpanel = new JPanel(); //Création d'une nouvelle JPanel
        jpanel.setBackground(Color.white); // Mise en place d'un fond blanc
        changerPanel(jpanel); //Remplacement du Body
        jLabelTitle.setText("");
    }
    
    /**
     * charge la page de création d'une demande de compétences
     */
    public void goToCreerDemandeCompetence(){
        changerPanel(new JPanelCreerDemandeCompetences(identifiantManager, service));
        jLabelTitle.setText("Création d'une demande de compétences");
    }
    
    /**
     * Charge la page visualisant les informations concernant l'équipe que dirige le manager
     */
    public void goToDetailEquipe(){
        try {
            //On Récupère les données
            DetailsEquipeVM viewModel = service.consulterLesDonneesDUneEquipe(identifiantManager); 
            //On prépare la jPanel
            JPanelDetailsEquipe panel = new JPanelDetailsEquipe(viewModel);
            //On remplace le Body
            changerPanel(panel);
            jLabelTitle.setText("Les données de mon équipe");
        } catch (IdentifiantInvalideException ex) {
            ErrorPopUp errorPopUp = new ErrorPopUp(ex.getMessage());
            Logger.getLogger(Canvas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Charge la page visualisant les information concernant les demandes de compétences créées par le manager
     */
    public void goToListeDemandeCompetence(){
        try {
            //On récupère les données
            List<DmdCompetencesVM> viewModel = service.consulterLesDemandesDeCompetencesDuManager(identifiantManager);
            //On prépare le panel conteneur
            JPanel panelListe = new JPanel(new GridLayout());
            //On prépare la JTable contenant les données
            JTable tableauDmdCompetence = new JTable(new DmdCompetenceTableModel(viewModel));
            for(int i = 0; i<tableauDmdCompetence.getColumnModel().getColumnCount(); i++){
                tableauDmdCompetence.getColumnModel().getColumn(i).setCellRenderer(new BlueTableColoredCellRenderer());
            }
            //On ajoute le tableau dans le panel
            panelListe.add(new JScrollPane(tableauDmdCompetence), new GridLayout());
            //On remplace le Body
            changerPanel(panelListe);
            jLabelTitle.setText("La liste de vos demandes");
        } catch (IdentifiantInvalideException ex) {
            ErrorPopUp errorPopUp = new ErrorPopUp(ex.getMessage());
            Logger.getLogger(Canvas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Créer s'il n'existe pas, ou récupère l'unique instance de classe Canvas
     * @return l'unique instance de Canvas (Mia-Manager)
     */
    public static Canvas getCanvasInstance(){
        if(canvas == null){
            try {
                canvas = new Canvas();
            } catch (NamingException ex) {
                ErrorPopUp errorPopUp = new ErrorPopUp(ex.getMessage());
                Logger.getLogger(Canvas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return canvas;
    }

    public void setIdentifiantManager(int identifiantManager) {
        this.identifiantManager = identifiantManager;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Canvas.getCanvasInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel boutons;
    private javax.swing.JButton jButtonDemandesDeCompetences;
    private javax.swing.JButton jButtonEquipe;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelTitreApplication;
    private javax.swing.JScrollPane jScrollPaneBody;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JPanel leftSplitBackground;
    private javax.swing.JPanel rightSplitBackground;
    // End of variables declaration//GEN-END:variables
}
